# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_latex"
  l3build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v3

      # 4. Install additional dependencies
      - run: apt-get update && apt-get install -y librsvg2-bin

      # 4. Setup TU-Logo by converting it to pdf and copying it to the template directory
      - name: "Setup TU-Logo"
        run: |
          mkdir -p "$(kpsewhich -var-value=TEXMFHOME)/tex/latex/local"
          curl -o tuda_logo.svg -L https://upload.wikimedia.org/wikipedia/de/2/24/TU_Darmstadt_Logo.svg\?download
          rsvg-convert -f pdf -o tuda_logo.pdf tuda_logo.svg
          mv tuda_logo.pdf "$(kpsewhich -var-value=TEXMFHOME)/tex/latex/local"
          texhash --verbose

      # 5. Run l3build
      - name: Run l3build
        run: l3build ctan -H

      # 6. Upload artifacts to GitHub
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: CTAN Archives
          path: "*.zip"
          if-no-files-found: error
